import matplotlib.pyplot as plt
import numpy
from PIL import Image
import numpy as np
def transferfunctions():
    f1 = Image.open('../resources/shepp256.png')
    F1 = np.fft.fftshift(np.fft.fft2(f1))
    h1 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/h1.png')
    h2 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/h2.png')
    h3 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/h3.png')
    H1 = np.fft.fftshift(np.fft.fft2(h1))
    H2 = np.fft.fftshift(np.fft.fft2(h2))
    H3 = np.fft.fftshift(np.fft.fft2(h3))
    F1H1 = F1*H1
    F1H2 = F1*H2
    F1H3 = F1*H3
    f1h1 = np.fft.ifftshift(np.fft.ifft2(F1H1))
    f1h2 = np.fft.ifftshift(np.fft.ifft2(F1H2))
    f1h3 = np.fft.ifftshift(np.fft.ifft2(F1H3))
    plt.figure(1)
    plt.gray()
    plt.subplot(241)
    plt.imshow(np.abs(f1))
    plt.title("f1")
    plt.subplot(242)
    plt.imshow(np.abs(f1h1))
    plt.title("f1h1")
    plt.subplot(243)
    plt.imshow(np.abs(f1h2))
    plt.title("f1h2")
    plt.subplot(244)
    plt.imshow(np.abs(f1h3))
    plt.title("f1h3")
    plt.subplot(245)
    plt.imshow(np.abs(np.log(F1)))
    plt.title("F1")
    plt.subplot(246)
    plt.imshow(np.abs(np.log(F1H1)))
    plt.title("F1H1")
    plt.subplot(247)
    plt.imshow(np.abs(np.log(F1H2)))
    plt.title("F1H2")
    plt.subplot(248)
    plt.imshow(np.abs(np.log(F1H3)))
    plt.title("F1H3")
    plt.show()
    return plt.figure(1)

def cascade():
    f1 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/shepp256.png')
    F1 = np.fft.fftshift(np.fft.fft2(f1))
    h1 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/h1.png')
    h2 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/h2.png')
    h3 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/h3.png')
    H1 = np.fft.fftshift(np.fft.fft2(h1))
    H2 = np.fft.fftshift(np.fft.fft2(h2))
    H3 = np.fft.fftshift(np.fft.fft2(h3))
    F1H1 = F1*H1
    F1H2 = F1H1*H2
    F1H3 = F1H2*H3
    f1h1 = np.fft.ifftshift(np.fft.ifft2(F1H1))
    f1h2 = np.fft.ifftshift(np.fft.ifft2(F1H2))
    f1h3 = np.fft.ifftshift(np.fft.ifft2(F1H3))
    plt.figure(1)
    plt.gray()
    plt.subplot(241)
    plt.imshow(np.abs(f1))
    plt.title("f1")
    plt.subplot(242)
    plt.imshow(np.abs(f1h1))
    plt.title("f1h1")
    plt.subplot(243)
    plt.imshow(np.abs(f1h2))
    plt.title("f1h2")
    plt.subplot(244)
    plt.imshow(np.abs(f1h3))
    plt.title("f1h3")
    plt.subplot(245)
    plt.imshow(np.abs(np.log(F1)))
    plt.title("F1")
    plt.subplot(246)
    plt.imshow(np.abs(np.log(F1H1)))
    plt.title("F1H1")
    plt.subplot(247)
    plt.imshow(np.abs(np.log(F1H2)))
    plt.title("F1H2")
    plt.subplot(248)
    plt.imshow(np.abs(np.log(F1H3)))
    plt.title("F1H3")
    plt.show()
    return plt.figure(1)

def exponentialdecay():
    numpy.seterr(divide='ignore')
    H4 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/H4.png')
    h4 = np.fft.ifftshift(np.fft.ifft2(H4))
    f1 = Image.open('D:/Workspace/2021 Year Project/MRI python/resources/shepp256.png')
    F1 = np.fft.fftshift(np.fft.fft2(f1))
    F1H4 = H4*F1
    f1h4 = np.fft.ifft2(F1H4)
    plt.figure(1)
    plt.gray()
    plt.subplot(231)
    plt.imshow(f1)
    plt.title("f1")
    plt.subplot(234)
    plt.imshow(np.log(np.abs(F1)))
    plt.title("F1")
    plt.subplot(232)
    plt.imshow(np.abs(h4))
    plt.title("h4")
    plt.subplot(235)
    plt.imshow(np.log(np.abs(H4)))
    plt.title("H4")
    plt.subplot(233)
    plt.imshow(np.abs(f1h4))
    plt.title("F1H4")
    plt.subplot(236)
    plt.imshow(np.log(np.abs(F1H4)))
    plt.title("F1H4")
    plt.show()
    numpy.seterr(divide='warn')
    return plt.figure(1)


if __name__ == "__main__":
    transferfunctions()
    cascade()
    exponentialdecay()

